// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#include "film-odb.hxx"

#include <cassert>
#include <cstring> // std::memcpy

#include <odb/cache-traits.hxx>
#include <odb/schema-catalog-impl.hxx>
#include <odb/details/shared-ptr.hxx>

#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/result.hxx>

namespace odb
{
  // Film
  //

  // genres_
  //

  const char access::object_traits< ::Film >::genres_traits::select_all_statement[] =
  "SELECT "
  "\"Genre_films\".\"object_id\""
  " FROM \"Genre_films\" WHERE \"Genre_films\".\"value\"=?";

  const char access::object_traits< ::Film >::genres_traits::insert_one_statement[] =
  "";

  const char access::object_traits< ::Film >::genres_traits::delete_all_statement[] =
  "";

  void access::object_traits< ::Film >::genres_traits::
  bind (sqlite::bind* b,
        const sqlite::bind* id,
        std::size_t id_size,
        cond_image_type& c)
  {
    ODB_POTENTIALLY_UNUSED (c);

    std::size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;
  }

  void access::object_traits< ::Film >::genres_traits::
  bind (sqlite::bind* b,
        const sqlite::bind* id,
        std::size_t id_size,
        data_image_type& d)
  {
    using namespace sqlite;

    statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    size_t n (0);

    // object_id
    //
    if (id != 0)
      std::memcpy (&b[n], id, id_size * sizeof (id[0]));
    n += id_size;

    // value
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &d.value_value;
    b[n].is_null = &d.value_null;
  }

  void access::object_traits< ::Film >::genres_traits::
  grow (data_image_type& i, bool* t)
  {
    bool grew (false);

    // value
    //
    t[0UL] = false;

    if (grew)
      i.version++;
  }

  void access::object_traits< ::Film >::genres_traits::
  init (value_type& v, const data_image_type& i, database& db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      typedef object_traits< ::Genre > obj_traits;
      typedef pointer_traits< value_type > ptr_traits;

      if (i.value_null)
        throw null_pointer ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i.value_value,
          i.value_null);

        v = ptr_traits::pointer_type (db, id);
      }
    }
  }

  void access::object_traits< ::Film >::genres_traits::
  insert_one (index_type, const value_type&, void*)
  {
  }

  bool access::object_traits< ::Film >::genres_traits::
  load_all (index_type&, value_type& v, void* d)
  {
    using namespace sqlite;

    statements_type& sts (*static_cast< statements_type* > (d));
    data_image_type& di (sts.data_image ());
    init (v, di, sts.connection ().database ());

    select_statement& st (sts.select_all_statement ());
    select_statement::result r (st.fetch ());
    if (r == select_statement::no_data)
    {
      st.free_result ();
      return false;
    }

    return true;
  }

  void access::object_traits< ::Film >::genres_traits::
  delete_all (void*)
  {
  }

  void access::object_traits< ::Film >::genres_traits::
  load (container_type& c,
        const sqlite::binding& id,
        statements_type& sts)
  {
    using namespace sqlite;

    binding& db (sts.data_image_binding ());
    if (id.version != sts.data_id_binding_version () || db.version == 0)
    {
      bind (db.bind, id.bind, id.count, sts.data_image ());
      sts.data_id_binding_version (id.version);
      db.version++;
      sts.select_image_binding ().version++;
    }

    binding& cb (sts.cond_image_binding ());
    if (id.version != sts.cond_id_binding_version () || cb.version == 0)
    {
      bind (cb.bind, id.bind, id.count, sts.cond_image ());
      sts.cond_id_binding_version (id.version);
      cb.version++;
    }

    select_statement& st (sts.select_all_statement ());
    st.execute ();
    select_statement::result r (st.fetch ());
    bool more (r != select_statement::no_data);

    if (!more)
      st.free_result ();

    sts.id_binding (id);
    functions_type& fs (sts.functions ());
    fs.ordered (false);
    container_traits_type::load (c, more, fs);
  }

  access::object_traits< ::Film >::id_type
  access::object_traits< ::Film >::
  id (const image_type& i)
  {
    id_type id;
    sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::set_value (
      id,
      i.id_value,
      i.id_null);

    return id;
  }

  bool access::object_traits< ::Film >::
  grow (image_type& i, bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = false;

    // name_
    //
    if (t[1UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // year_
    //
    t[2UL] = false;

    // rating_
    //
    t[3UL] = false;

    // length_
    //
    t[4UL] = false;

    return grew;
  }

  void access::object_traits< ::Film >::
  bind (sqlite::bind* b, image_type& i, sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // name_
    //
    b[n].type = sqlite::bind::text;
    b[n].buffer = i.name_value.data ();
    b[n].size = &i.name_size;
    b[n].capacity = i.name_value.capacity ();
    b[n].is_null = &i.name_null;
    n++;

    // year_
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.year_value;
    b[n].is_null = &i.year_null;
    n++;

    // rating_
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.rating_value;
    b[n].is_null = &i.rating_null;
    n++;

    // length_
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.length_value;
    b[n].is_null = &i.length_null;
    n++;
  }

  void access::object_traits< ::Film >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits< ::Film >::
  init (image_type& i, const object_type& o, sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // id_
    //
    if (sk == statement_insert)
    {
      sqlite::value_traits<
          long unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        i.id_null,
        o.id_);
    }

    // name_
    //
    {
      std::size_t cap (i.name_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i.name_value,
        i.name_size,
        i.name_null,
        o.name_);
      grew = grew || (cap != i.name_value.capacity ());
    }

    // year_
    //
    {
      sqlite::value_traits<
          short unsigned int,
          sqlite::id_integer >::set_image (
        i.year_value,
        i.year_null,
        o.year_);
    }

    // rating_
    //
    {
      sqlite::value_traits<
          short unsigned int,
          sqlite::id_integer >::set_image (
        i.rating_value,
        i.rating_null,
        o.rating_);
    }

    // length_
    //
    {
      sqlite::value_traits<
          short unsigned int,
          sqlite::id_integer >::set_image (
        i.length_value,
        i.length_null,
        o.length_);
    }

    return grew;
  }

  void access::object_traits< ::Film >::
  init (object_type& o, const image_type& i, database& db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    sqlite::value_traits<
        long unsigned int,
        sqlite::id_integer >::set_value (
      o.id_,
      i.id_value,
      i.id_null);

    // name_
    //
    sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::set_value (
      o.name_,
      i.name_value,
      i.name_size,
      i.name_null);

    // year_
    //
    sqlite::value_traits<
        short unsigned int,
        sqlite::id_integer >::set_value (
      o.year_,
      i.year_value,
      i.year_null);

    // rating_
    //
    sqlite::value_traits<
        short unsigned int,
        sqlite::id_integer >::set_value (
      o.rating_,
      i.rating_value,
      i.rating_null);

    // length_
    //
    sqlite::value_traits<
        short unsigned int,
        sqlite::id_integer >::set_value (
      o.length_,
      i.length_value,
      i.length_null);
  }

  void access::object_traits< ::Film >::
  init (id_image_type& i, const id_type& id)
  {
    {
      sqlite::value_traits<
          long unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        i.id_null,
        id);
    }
  }

  struct access::object_traits< ::Film >::container_statement_cache_type
  {
    sqlite::container_statements_impl< genres_traits > genres_;

    container_statement_cache_type (sqlite::connection& c)
    : genres_ (c)
    {
    }
  };

  const char access::object_traits< ::Film >::persist_statement[] =
  "INSERT INTO \"Film\" ("
  "\"id\","
  "\"name\","
  "\"year\","
  "\"rating\","
  "\"length\")"
  " VALUES (?,?,?,?,?)";

  const char access::object_traits< ::Film >::find_statement[] =
  "SELECT "
  "\"Film\".\"id\","
  "\"Film\".\"name\","
  "\"Film\".\"year\","
  "\"Film\".\"rating\","
  "\"Film\".\"length\""
  " FROM \"Film\""
  " WHERE \"Film\".\"id\"=?";

  const char access::object_traits< ::Film >::update_statement[] =
  "UPDATE \"Film\" SET "
  "\"name\"=?,"
  "\"year\"=?,"
  "\"rating\"=?,"
  "\"length\"=?"
  " WHERE \"id\"=?";

  const char access::object_traits< ::Film >::erase_statement[] =
  "DELETE FROM \"Film\""
  " WHERE \"id\"=?";

  const char access::object_traits< ::Film >::query_statement[] =
  "SELECT "
  "\"Film\".\"id\","
  "\"Film\".\"name\","
  "\"Film\".\"year\","
  "\"Film\".\"rating\","
  "\"Film\".\"length\""
  " FROM \"Film\""
  " ";

  const char access::object_traits< ::Film >::erase_query_statement[] =
  "DELETE FROM \"Film\""
  " ";

  const char access::object_traits< ::Film >::table_name[] =
  "\"Film\"";

  void access::object_traits< ::Film >::
  persist (database&, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());
    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.id_null = true;

    if (im.version != sts.insert_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = static_cast< id_type > (st.id ());
  }

  void access::object_traits< ::Film >::
  update (database&, const object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, obj.id_);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.update_id_image_version () || idb.version == 0)
    {
      if (i.version != sts.id_image_version () || idb.version == 0)
      {
        bind (idb.bind, i);
        sts.id_image_version (i.version);
        idb.version++;
      }

      sts.update_id_image_version (i.version);

      if (!u)
        imb.version++;
    }

    if (sts.update_statement ().execute () == 0)
      throw object_not_persistent ();
  }

  void access::object_traits< ::Film >::
  erase (database&, const id_type& id)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();
  }

  access::object_traits< ::Film >::pointer_type
  access::object_traits< ::Film >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());
    object_statements< object_type >::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory< object_type, pointer_type  >::create ());
    pointer_traits< pointer_type >::guard pg (p);
    pointer_cache_traits< pointer_type >::insert_guard ig (
      pointer_cache_traits< pointer_type >::insert (db, id, p));
    object_type& obj (pointer_traits< pointer_type >::get_ref (p));

    if (l.locked ())
    {
      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), db);
      load_ (sts, obj);
      sts.load_delayed ();
      l.unlock ();
      callback (db, obj, callback_event::post_load);
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits< ::Film >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    object_statements< object_type >::auto_lock l (sts);

    if (!find_ (sts, id))
      return false;

    reference_cache_traits< object_type >::insert_guard ig (
      reference_cache_traits< object_type >::insert (db, id, obj));

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), db);
    load_ (sts, obj);
    sts.load_delayed ();
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    ig.release ();
    return true;
  }

  bool access::object_traits< ::Film >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    object_statements< object_type >::auto_lock l (sts);

    if (!find_ (sts, obj.id_))
      return false;

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), db);
    load_ (sts, obj);
    sts.load_delayed ();
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits< ::Film >::
  find_ (sqlite::object_statements< object_type >& sts, const id_type& id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());
    st.execute ();
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    st.free_result ();
    return r != select_statement::no_data;
  }

  void access::object_traits< ::Film >::
  load_ (sqlite::object_statements< object_type >& sts, object_type& obj)
  {
    sqlite::binding& idb (sts.id_image_binding ());

    genres_traits::load (
      obj.genres_,
      idb,
      sts.container_statment_cache ().genres_);
  }

  result< access::object_traits< ::Film >::object_type >
  access::object_traits< ::Film >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    object_statements< object_type >& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement + q.clause (),
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits< ::Film >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    delete_statement st (
      conn,
      erase_query_statement + q.clause (),
      q.parameters_binding ());

    return st.execute ();
  }

  bool access::object_traits< ::Film >::
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("DROP TABLE IF EXISTS \"Film\"");

          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"Film\" (\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,\n"
                      "  \"name\" TEXT NOT NULL,\n"
                      "  \"year\" INTEGER NOT NULL,\n"
                      "  \"rating\" INTEGER NOT NULL,\n"
                      "  \"length\" INTEGER NOT NULL)");

          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_entry
  schema_catalog_entry_Film_ (
    "",
    &access::object_traits< ::Film >::create_schema);

  // film_stat
  //

  bool access::view_traits< ::film_stat >::
  grow (image_type& i, bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // count
    //
    t[0UL] = false;

    return grew;
  }

  void access::view_traits< ::film_stat >::
  bind (sqlite::bind* b, image_type& i)
  {
    using namespace sqlite;

    sqlite::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // count
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.count_value;
    b[n].is_null = &i.count_null;
    n++;
  }

  void access::view_traits< ::film_stat >::
  init (view_type& o, const image_type& i, database& db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // count
    //
    sqlite::value_traits<
        ::size_t,
        sqlite::id_integer >::set_value (
      o.count,
      i.count_value,
      i.count_null);
  }

  access::view_traits< ::film_stat >::query_base_type
  access::view_traits< ::film_stat >::
  query_statement (const query_base_type& q)
  {
    query_base_type r (
      "SELECT "
      "count(\"Film\".\"id\")"
    );

    r += "FROM \"Film\"";

    r += q.clause_prefix ();
    r += q;

    return r;
  }

  result< access::view_traits< ::film_stat >::view_type >
  access::view_traits< ::film_stat >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    view_statements< view_type >& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (query_statement (q));
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        qs.clause (),
        qs.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) sqlite::view_result_impl<view_type> (
        qs, st, sts));

    return result<view_type> (r);
  }
}

// Begin epilogue.
//
//
// End epilogue.

#include <odb/post.hxx>
